// export const GAME_COMPONENTS = {
//   RENDERER: "RENDERER",
//   KEYBOARD: "KEYBOARD",
//   PLAYER: "PLAYER",
//   GAME_AREA: "GAME_AREA",
//   EFFECTS_MANAGER: "EFFECTS_MANAGER",
//   COLLISION_MANAGER: "COLLISION_MANAGER",
//   PARTICLE_MANAGER: "PARTICLE_MANAGER",
// };
